/**
 * PDF Export Utility
 * Generates PDF reports using browser print or canvas-based generation
 */

export interface PdfExportConfig {
  title: string;
  subtitle?: string;
  filename: string;
  metadata?: Array<{ label: string; value: string }>;
  orientation?: 'portrait' | 'landscape';
}

export interface PdfTableSection {
  title: string;
  headers: string[];
  rows: Array<Array<string | number>>;
  cellStyles?: Array<(value: string | number, rowIndex: number) => React.CSSProperties | undefined>;
}

const PDF_STYLES = `
  @media print {
    @page {
      size: A4;
      margin: 10mm;
    }
    body {
      -webkit-print-color-adjust: exact !important;
      print-color-adjust: exact !important;
    }
    .no-print { display: none !important; }
    .page-break { page-break-before: always; }
  }

  * {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
  }

  body {
    font-family: 'Segoe UI', Arial, sans-serif;
    font-size: 11px;
    line-height: 1.4;
    color: #333;
    padding: 15px 10px;
  }

  .header {
    text-align: center;
    margin-bottom: 15px;
    padding-bottom: 12px;
    border-bottom: 2px solid #1a56db;
  }

  .header h1 {
    color: #1a56db;
    font-size: 22px;
    margin-bottom: 5px;
  }

  .header .subtitle {
    color: #666;
    font-size: 12px;
  }

  .metadata {
    display: flex;
    flex-wrap: wrap;
    gap: 15px;
    background: #f8fafc;
    padding: 10px 12px;
    border-radius: 6px;
    margin-bottom: 15px;
    font-size: 11px;
  }

  .metadata-item {
    display: flex;
    gap: 5px;
  }

  .metadata-item strong {
    color: #374151;
  }

  .section {
    margin-bottom: 20px;
  }

  .section h2 {
    color: #1f2937;
    font-size: 14px;
    padding: 8px 0;
    border-bottom: 1px solid #e5e7eb;
    margin-bottom: 8px;
  }

  table {
    width: 100%;
    border-collapse: collapse;
    font-size: 10px;
    table-layout: fixed;
  }

  th, td {
    border: 1px solid #d1d5db;
    padding: 6px 8px;
    text-align: left;
    word-wrap: break-word;
  }

  th {
    background-color: #1a56db;
    font-weight: 600;
    color: #ffffff;
  }

  tr:nth-child(even) {
    background-color: #f9fafb;
  }

  .status-open, .status-pending { color: #dc2626; }
  .status-resolved, .status-completed { color: #16a34a; }
  .status-in_progress { color: #ea580c; }

  .priority-critical { color: #dc2626; font-weight: bold; }
  .priority-high { color: #ea580c; font-weight: 600; }
  .priority-medium { color: #ca8a04; }
  .priority-low { color: #16a34a; }

  .text-success { color: #16a34a; }
  .text-danger { color: #dc2626; }
  .text-warning { color: #ca8a04; }

  .footer {
    margin-top: 20px;
    padding-top: 10px;
    border-top: 1px solid #e5e7eb;
    font-size: 9px;
    color: #666;
    text-align: center;
  }
`;

/**
 * Generates a print-ready HTML document for PDF export
 */
export function generatePdfHtml(
  config: PdfExportConfig,
  sections: PdfTableSection[]
): string {
  const metadataHtml = config.metadata?.map(
    item => `<div class="metadata-item"><strong>${item.label}:</strong> <span>${item.value}</span></div>`
  ).join('\n      ') || '';

  const sectionsHtml = sections.map(section => `
    <div class="section">
      <h2>${section.title}</h2>
      <table>
        <thead>
          <tr>${section.headers.map(h => `<th>${h}</th>`).join('')}</tr>
        </thead>
        <tbody>
          ${section.rows.map((row, rowIndex) => `
          <tr>${row.map((cell, cellIndex) => {
            const styleObj = section.cellStyles?.[cellIndex]?.(cell, rowIndex);
            const styleStr = styleObj ? ` style="${Object.entries(styleObj).map(([k, v]) => `${k.replace(/([A-Z])/g, '-$1').toLowerCase()}:${v}`).join(';')}"` : '';
            return `<td${styleStr}>${cell}</td>`;
          }).join('')}</tr>`).join('')}
        </tbody>
      </table>
    </div>`).join('\n');

  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>${config.title}</title>
  <style>${PDF_STYLES}</style>
</head>
<body>
  <div class="header">
    <h1>${config.title}</h1>
    ${config.subtitle ? `<div class="subtitle">${config.subtitle}</div>` : ''}
  </div>

  ${metadataHtml ? `<div class="metadata">\n      ${metadataHtml}\n    </div>` : ''}

  ${sectionsHtml}

  <div class="footer">
    Generated by LINCE Water Treatment Monitoring System - ${new Date().toLocaleString()}
  </div>
</body>
</html>`;
}

/**
 * Opens print dialog with the PDF content
 * This is the most reliable cross-browser method
 */
export function exportToPdf(
  config: PdfExportConfig,
  sections: PdfTableSection[]
): void {
  const html = generatePdfHtml(config, sections);

  // Create a new window for printing
  const printWindow = window.open('', '_blank', 'width=800,height=600');

  if (printWindow) {
    printWindow.document.write(html);
    printWindow.document.close();

    // Wait for content to load then print
    printWindow.onload = () => {
      setTimeout(() => {
        printWindow.focus();
        printWindow.print();
      }, 250);
    };
  } else {
    // Fallback: download as HTML if popup blocked
    console.warn('Popup blocked. Downloading as HTML instead.');
    const blob = new Blob([html], { type: 'text/html;charset=utf-8;' });
    const link = document.createElement('a');
    link.href = URL.createObjectURL(blob);
    link.download = `${config.filename}.html`;
    link.click();
    URL.revokeObjectURL(link.href);
  }
}

/**
 * Downloads the content as HTML (fallback for PDF)
 */
export function downloadAsPrintableHtml(
  config: PdfExportConfig,
  sections: PdfTableSection[]
): void {
  const html = generatePdfHtml(config, sections);
  const blob = new Blob([html], { type: 'text/html;charset=utf-8;' });
  const link = document.createElement('a');
  link.href = URL.createObjectURL(blob);
  link.download = `${config.filename}.html`;
  link.click();
  URL.revokeObjectURL(link.href);
}
