/**
 * PDF Export Utility
 * Generates PDF reports using jsPDF and jspdf-autotable
 */
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export interface PdfExportConfig {
  title: string;
  subtitle?: string;
  filename: string;
  metadata?: Array<{ label: string; value: string }>;
  orientation?: 'portrait' | 'landscape';
}

export interface PdfTableSection {
  title: string;
  headers: string[];
  rows: Array<Array<string | number>>;
}

/**
 * Generates and downloads a PDF document with tables
 */
export function exportToPdf(
  config: PdfExportConfig,
  sections: PdfTableSection[]
): void {
  const doc = new jsPDF({
    orientation: config.orientation || 'portrait',
    unit: 'mm',
    format: 'a4'
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 10;
  let currentY = margin;

  // Title
  doc.setFontSize(20);
  doc.setTextColor(26, 86, 219); // #1a56db
  doc.text(config.title, pageWidth / 2, currentY + 8, { align: 'center' });
  currentY += 12;

  // Subtitle
  if (config.subtitle) {
    doc.setFontSize(12);
    doc.setTextColor(102, 102, 102);
    doc.text(config.subtitle, pageWidth / 2, currentY + 4, { align: 'center' });
    currentY += 8;
  }

  // Header line
  doc.setDrawColor(26, 86, 219);
  doc.setLineWidth(0.5);
  doc.line(margin, currentY + 2, pageWidth - margin, currentY + 2);
  currentY += 8;

  // Metadata box
  if (config.metadata && config.metadata.length > 0) {
    doc.setFillColor(248, 250, 252); // #f8fafc
    doc.roundedRect(margin, currentY, pageWidth - margin * 2, 12, 2, 2, 'F');

    doc.setFontSize(9);
    doc.setTextColor(55, 65, 81); // #374151

    const metadataText = config.metadata.map(m => `${m.label}: ${m.value}`).join('    |    ');
    doc.text(metadataText, pageWidth / 2, currentY + 7, { align: 'center' });
    currentY += 18;
  }

  // Sections with tables
  sections.forEach((section) => {
    // Check if we need a new page
    if (currentY > pageHeight - 50) {
      doc.addPage();
      currentY = margin;
    }

    // Section title
    doc.setFontSize(12);
    doc.setTextColor(31, 41, 55); // #1f2937
    doc.text(section.title, margin, currentY + 5);

    // Section title underline
    doc.setDrawColor(229, 231, 235); // #e5e7eb
    doc.setLineWidth(0.3);
    doc.line(margin, currentY + 7, pageWidth - margin, currentY + 7);
    currentY += 10;

    // Table
    autoTable(doc, {
      startY: currentY,
      head: [section.headers],
      body: section.rows.map(row => row.map(cell => String(cell))),
      margin: { left: margin, right: margin },
      styles: {
        fontSize: 8,
        cellPadding: 2,
        overflow: 'linebreak',
        lineColor: [209, 213, 219], // #d1d5db
        lineWidth: 0.1,
      },
      headStyles: {
        fillColor: [26, 86, 219], // #1a56db
        textColor: [255, 255, 255],
        fontStyle: 'bold',
        halign: 'left',
      },
      alternateRowStyles: {
        fillColor: [249, 250, 251], // #f9fafb
      },
      bodyStyles: {
        textColor: [51, 51, 51],
      },
      tableWidth: 'auto',
      didDrawPage: (data) => {
        // Update currentY after table is drawn
        if (data.cursor) {
          currentY = data.cursor.y + 8;
        }
      },
    });

    // Get the final Y position after the table
    const finalY = (doc as any).lastAutoTable?.finalY || currentY;
    currentY = finalY + 10;
  });

  // Footer on last page
  const footerText = `Generated by LINCE Water Treatment Monitoring System - ${new Date().toLocaleString()}`;
  doc.setFontSize(8);
  doc.setTextColor(102, 102, 102);
  doc.text(footerText, pageWidth / 2, pageHeight - 8, { align: 'center' });

  // Save the PDF
  const filename = config.filename.endsWith('.pdf') ? config.filename : `${config.filename}.pdf`;
  doc.save(filename);
}

/**
 * Generates PDF and returns as Blob (useful for preview or upload)
 */
export function generatePdfBlob(
  config: PdfExportConfig,
  sections: PdfTableSection[]
): Blob {
  const doc = new jsPDF({
    orientation: config.orientation || 'portrait',
    unit: 'mm',
    format: 'a4'
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 10;
  let currentY = margin;

  // Title
  doc.setFontSize(20);
  doc.setTextColor(26, 86, 219);
  doc.text(config.title, pageWidth / 2, currentY + 8, { align: 'center' });
  currentY += 12;

  // Subtitle
  if (config.subtitle) {
    doc.setFontSize(12);
    doc.setTextColor(102, 102, 102);
    doc.text(config.subtitle, pageWidth / 2, currentY + 4, { align: 'center' });
    currentY += 8;
  }

  // Header line
  doc.setDrawColor(26, 86, 219);
  doc.setLineWidth(0.5);
  doc.line(margin, currentY + 2, pageWidth - margin, currentY + 2);
  currentY += 8;

  // Metadata
  if (config.metadata && config.metadata.length > 0) {
    doc.setFillColor(248, 250, 252);
    doc.roundedRect(margin, currentY, pageWidth - margin * 2, 12, 2, 2, 'F');

    doc.setFontSize(9);
    doc.setTextColor(55, 65, 81);

    const metadataText = config.metadata.map(m => `${m.label}: ${m.value}`).join('    |    ');
    doc.text(metadataText, pageWidth / 2, currentY + 7, { align: 'center' });
    currentY += 18;
  }

  // Sections
  sections.forEach((section) => {
    if (currentY > pageHeight - 50) {
      doc.addPage();
      currentY = margin;
    }

    doc.setFontSize(12);
    doc.setTextColor(31, 41, 55);
    doc.text(section.title, margin, currentY + 5);

    doc.setDrawColor(229, 231, 235);
    doc.setLineWidth(0.3);
    doc.line(margin, currentY + 7, pageWidth - margin, currentY + 7);
    currentY += 10;

    autoTable(doc, {
      startY: currentY,
      head: [section.headers],
      body: section.rows.map(row => row.map(cell => String(cell))),
      margin: { left: margin, right: margin },
      styles: {
        fontSize: 8,
        cellPadding: 2,
        overflow: 'linebreak',
        lineColor: [209, 213, 219],
        lineWidth: 0.1,
      },
      headStyles: {
        fillColor: [26, 86, 219],
        textColor: [255, 255, 255],
        fontStyle: 'bold',
        halign: 'left',
      },
      alternateRowStyles: {
        fillColor: [249, 250, 251],
      },
      bodyStyles: {
        textColor: [51, 51, 51],
      },
    });

    const finalY = (doc as any).lastAutoTable?.finalY || currentY;
    currentY = finalY + 10;
  });

  // Footer
  const footerText = `Generated by LINCE Water Treatment Monitoring System - ${new Date().toLocaleString()}`;
  doc.setFontSize(8);
  doc.setTextColor(102, 102, 102);
  doc.text(footerText, pageWidth / 2, pageHeight - 8, { align: 'center' });

  return doc.output('blob');
}
